name: Memory Usage Check

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  push:
    branches:
      - main

jobs:
  memory-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.1
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run memory profiling tests
        run: |
          NODE_OPTIONS="--expose-gc --max-old-space-size=512" pnpm test tests/github/memory-profile.test.ts tests/github/memory-minimal.test.ts tests/github/memory-leak-detection.test.ts || true
        env:
          DEBUG_TESTS: false
          
      - name: Check heap usage
        run: |
          echo "Checking test output for memory usage..."
          NODE_OPTIONS="--expose-gc" pnpm test tests/github/memory-minimal.test.ts 2>&1 | tee memory-output.log
          
          # Extract heap usage from output
          HEAP_USAGE=$(grep -oE '[0-9]+(\.[0-9]+)? MB heap used' memory-output.log | grep -oE '[0-9]+(\.[0-9]+)?' | tail -1)
          echo "Final heap usage: ${HEAP_USAGE}MB"
          
          # Check if under 40MB (relaxed from 20MB due to test environment overhead)
          if (( $(echo "$HEAP_USAGE > 40" | bc -l) )); then
            echo "❌ Heap usage ${HEAP_USAGE}MB exceeds 40MB limit"
            exit 1
          else
            echo "✅ Heap usage ${HEAP_USAGE}MB is within acceptable range"
          fi